### ISSUE TITLE
Implement Dank Meter

### ISSUE THREAD

**Issue by RedbackThomson** [RedbackThomson/OsuCelebrity#2]
The ability for users to vote !dank on a particular streamer. A dank is a measure of popularity for a particular player. After a particular amount the time should be increased to allow the popular player more time to stream. There should be a max limit to the dank to make sure the next player is eventually reached.

**Comment by RedbackThomson** [comment]
Only for Twitch users, since it's not relevant for in-game users.

**Comment by Tillerino** [comment]
(although you send !dank to the osu bot for that matter)

**Comment by RedbackThomson** [comment]
But what's the point of sending it to the bot in game? You're meant to be watching it from the stream

**Comment by Tillerino** [comment]
Maybe you don't have a twitch account
