### ISSUE TITLE
Upgrade Output

### ISSUE THREAD

**Issue by RedbackThomson** [RedbackThomson/OsuCelebrity#3]
Current output is a shoddy method inside the [OsuApplication class](https://github.com/RedbackThomson/OsuCelebrity/blob/structure/osuCelebrity-osu/src/main/java/me/reddev/osucelebrity/osu/OsuApplication.java#L61). This should be extended out to it's own interface and class so we can hook up more output methods such as remaining time and current song title as well as to different sources (maybe POST).

**Comment by Tillerino** [comment]
This was realized through a simple HTTP API, see `me.reddev.osucelebrity.core.api.CurrentPlayerService`
